#!/usr/bin/env node
// Writes src/events_gen.ts from spec/events.yaml.
//
// TypeScript's counterpart to internal/gen/events (see that package's
// main.go): same source file, same idea (a closed set of literal event
// names a typo cannot slip past the compiler), same --check flag for
// generate-check/CI. It cannot use go/format or the ident.Export helper
// those are Go-only -- this script ports the identifier-export rule
// inline (see exportName below) and pretty-prints by hand (the output is
// simple enough that a formatter buys nothing).
//
// Unlike bundle-spec.mjs, this is NOT purely a build-time step: its
// output is committed (src/events_gen.ts ships in the package and is
// read directly by src/events.ts), so `pnpm build` runs it but so does
// `make generate-check` in CI, against the working tree, with no build
// step in between.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import YAML from "yaml";

const here = path.dirname(fileURLToPath(import.meta.url));
const tsRoot = path.resolve(here, "..");
const repoRoot = path.resolve(tsRoot, "..");

const args = process.argv.slice(2);
const check = args.includes("--check");
const inArg = args.find((a) => a.startsWith("--in="));
const outArg = args.find((a) => a.startsWith("--out="));
const inPath = inArg ? path.resolve(repoRoot, inArg.slice("--in=".length)) : path.join(repoRoot, "spec", "events.yaml");
const outPath = outArg ? path.resolve(repoRoot, outArg.slice("--out=".length)) : path.join(tsRoot, "src", "events_gen.ts");

// exportName mirrors internal/gen/ident.Export: split on '_', '-', '.',
// upper-case the first letter of each part, join. It turns a wire name
// that is not a valid identifier on its own into one that is, for the
// named-constant exports below. Every catalog event is PascalCase today,
// so this is a no-op for all of them, but host-side wire names are not
// (OpenCode raises `tool.execute.before`) and the catalog is free to admit
// one. The string literal union itself never needs this -- TypeScript
// string literal types accept any text -- but the constants are ordinary
// identifiers and must be spelled like one.
function exportName(name) {
  const parts = name.split(/[_\-.]/).filter((p) => p.length > 0);
  return parts.map((p) => p[0].toUpperCase() + p.slice(1)).join("");
}

function main() {
  const raw = readFileSync(inPath, "utf8");
  const doc = YAML.parse(raw);
  const events = doc.events;
  if (!Array.isArray(events) || events.length === 0) {
    console.error(`gen-events: no events found in ${inPath}`);
    process.exit(1);
  }

  const names = events.map((e) => e.name);

  const lines = [];
  lines.push("// Code generated by ts/scripts/gen-events.mjs from spec/events.yaml; DO NOT EDIT.");
  lines.push("");
  lines.push("/**");
  lines.push(" * Every canonical event name in spec/events.yaml, as a closed string-literal");
  lines.push(" * union. Mirrors the generated constants in events_gen.go: a typo'd event");
  lines.push(" * name here fails to compile instead of silently falling through a switch's");
  lines.push(" * default case.");
  lines.push(" */");
  lines.push("export type CanonicalEvent =");
  for (const name of names) {
    lines.push(`  | ${JSON.stringify(name)}`);
  }
  lines.push("  ;");
  lines.push("");
  lines.push("/** Every canonical event name, in catalog order. */");
  lines.push("export const allCanonicalEvents: readonly CanonicalEvent[] = [");
  for (const name of names) {
    lines.push(`  ${JSON.stringify(name)},`);
  }
  lines.push("];");
  lines.push("");
  lines.push("// Named constants, one per event, mirroring axon.Event<Name> in events_gen.go.");
  for (const e of events) {
    const doc_ = (e.description ?? "").trim().replace(/\s+/g, " ");
    lines.push(`/** ${doc_} */`);
    lines.push(`export const Event${exportName(e.name)}: CanonicalEvent = ${JSON.stringify(e.name)};`);
  }
  lines.push("");

  const output = lines.join("\n");

  if (check) {
    let current;
    try {
      current = readFileSync(outPath, "utf8");
    } catch {
      current = null;
    }
    if (current !== output) {
      console.error(`gen-events: ${path.relative(repoRoot, outPath)} is stale; run \`pnpm gen:events\` (or \`pnpm build\`)`);
      process.exit(1);
    }
    return;
  }

  writeFileSync(outPath, output, "utf8");
  console.log(`gen-events: wrote ${path.relative(repoRoot, outPath)} (${names.length} events)`);
}

main();
