// Code generated by internal/gen/events from spec/events.yaml; DO NOT EDIT.

package axon

const (
	// EventSessionStart: Session begins or resumes.
	EventSessionStart Event = "SessionStart"
	// EventSessionEnd: Session terminates (graceful or forced).
	EventSessionEnd Event = "SessionEnd"
	// EventUserPromptSubmit: User submits a prompt before the model processes it.
	EventUserPromptSubmit Event = "UserPromptSubmit"
	// EventPreToolUse: Before a tool call executes; handler can block.
	EventPreToolUse Event = "PreToolUse"
	// EventPostToolUse: After a tool call succeeds.
	EventPostToolUse Event = "PostToolUse"
	// EventPostToolUseFailure: After a tool call fails.
	EventPostToolUseFailure Event = "PostToolUseFailure"
	// EventPermissionRequest: Permission dialog appears for a tool call.
	EventPermissionRequest Event = "PermissionRequest"
	// EventPermissionDenied: Tool call denied by auto-mode classifier or user.
	EventPermissionDenied Event = "PermissionDenied"
	// EventNotification: CLI sends a user-facing notification.
	EventNotification Event = "Notification"
	// EventSubagentStart: Subagent spawned by the main agent.
	EventSubagentStart Event = "SubagentStart"
	// EventSubagentStop: Subagent finishes execution.
	EventSubagentStop Event = "SubagentStop"
	// EventTaskCreated: Task created via TaskCreate tool or equivalent.
	EventTaskCreated Event = "TaskCreated"
	// EventTaskCompleted: Task marked completed.
	EventTaskCompleted Event = "TaskCompleted"
	// EventStop: Model finishes responding for this turn.
	EventStop Event = "Stop"
	// EventStopFailure: Turn ends due to API error or internal failure.
	EventStopFailure Event = "StopFailure"
	// EventTeammateIdle: Agent-team teammate going idle (multi-agent only).
	EventTeammateIdle Event = "TeammateIdle"
	// EventInstructionsLoaded: CLAUDE.md or equivalent rules file loaded/reloaded.

	EventInstructionsLoaded Event = "InstructionsLoaded"
	// EventConfigChange: Config file changes during a session.
	EventConfigChange Event = "ConfigChange"
	// EventCwdChanged: Working directory changes (e.g. via cd).
	EventCwdChanged Event = "CwdChanged"
	// EventFileChanged: Watched file changes on disk.
	EventFileChanged Event = "FileChanged"
	// EventWorktreeCreate: Git worktree created.
	EventWorktreeCreate Event = "WorktreeCreate"
	// EventWorktreeRemove: Git worktree removed.
	EventWorktreeRemove Event = "WorktreeRemove"
	// EventPreCompact: Before context compaction begins.
	EventPreCompact Event = "PreCompact"
	// EventPostCompact: After context compaction completes.
	EventPostCompact Event = "PostCompact"
	// EventElicitation: MCP server requests user input.
	EventElicitation Event = "Elicitation"
	// EventElicitationResult: User responds to MCP elicitation request.
	EventElicitationResult Event = "ElicitationResult"
	// EventBeforeToolSelection: Before model picks which tool to call (Gemini-only).

	EventBeforeToolSelection Event = "BeforeToolSelection"
	// EventLspDiagnostics: LSP diagnostics arrived (OpenCode-only).
	EventLspDiagnostics Event = "LspDiagnostics"
	// EventSessionDiff: Session code diff computed (OpenCode-only).
	EventSessionDiff Event = "SessionDiff"
	// EventSessionStatus: Session status transition (OpenCode-only).
	EventSessionStatus Event = "SessionStatus"
	// EventMemoryRead: Derived event — Read tool call targeting a canonical memory path (CLAUDE.md, MEMORY.md, .claude/memory/**, agent memory).

	EventMemoryRead Event = "MemoryRead"
	// EventMemoryWrite: Derived event — Write/Edit/NotebookEdit tool call targeting a canonical memory path. Same path regex as MemoryRead.

	EventMemoryWrite Event = "MemoryWrite"
)

// allEventConstants lists every generated constant, in catalog order.
var allEventConstants = []Event{
	EventSessionStart,
	EventSessionEnd,
	EventUserPromptSubmit,
	EventPreToolUse,
	EventPostToolUse,
	EventPostToolUseFailure,
	EventPermissionRequest,
	EventPermissionDenied,
	EventNotification,
	EventSubagentStart,
	EventSubagentStop,
	EventTaskCreated,
	EventTaskCompleted,
	EventStop,
	EventStopFailure,
	EventTeammateIdle,
	EventInstructionsLoaded,
	EventConfigChange,
	EventCwdChanged,
	EventFileChanged,
	EventWorktreeCreate,
	EventWorktreeRemove,
	EventPreCompact,
	EventPostCompact,
	EventElicitation,
	EventElicitationResult,
	EventBeforeToolSelection,
	EventLspDiagnostics,
	EventSessionDiff,
	EventSessionStatus,
	EventMemoryRead,
	EventMemoryWrite,
}
