// Code generated by internal/gen/hosts from spec/hosts; DO NOT EDIT.

package axon

const (
	HostAider       = "aider"
	HostAmp         = "amp"
	HostAntigravity = "antigravity"
	HostClaude      = "claude"
	HostCodex       = "codex"
	HostCopilot     = "copilot"
	HostCrush       = "crush"
	HostCursorAgent = "cursor-agent"
	HostGemini      = "gemini"
	HostGoose       = "goose"
	HostKimi        = "kimi"
	HostOpencode    = "opencode"
	HostOpenhands   = "openhands"
	HostQwen        = "qwen"
	HostTabnine     = "tabnine"
	HostVibe        = "vibe"
	HostWindsurf    = "windsurf"
)

// allHostNames lists every generated host directory name, sorted.
var allHostNames = []string{
	"aider",
	"amp",
	"antigravity",
	"claude",
	"codex",
	"copilot",
	"crush",
	"cursor-agent",
	"gemini",
	"goose",
	"kimi",
	"opencode",
	"openhands",
	"qwen",
	"tabnine",
	"vibe",
	"windsurf",
}
