// Code generated by ts/scripts/gen-events.mjs from spec/events.yaml; DO NOT EDIT.

/**
 * Every canonical event name in spec/events.yaml, as a closed string-literal
 * union. Mirrors the generated constants in events_gen.go: a typo'd event
 * name here fails to compile instead of silently falling through a switch's
 * default case.
 */
export type CanonicalEvent =
  | "SessionStart"
  | "SessionEnd"
  | "UserPromptSubmit"
  | "PreToolUse"
  | "PostToolUse"
  | "PostToolUseFailure"
  | "PermissionRequest"
  | "PermissionDenied"
  | "Notification"
  | "SubagentStart"
  | "SubagentStop"
  | "TaskCreated"
  | "TaskCompleted"
  | "Stop"
  | "StopFailure"
  | "TeammateIdle"
  | "InstructionsLoaded"
  | "ConfigChange"
  | "CwdChanged"
  | "FileChanged"
  | "WorktreeCreate"
  | "WorktreeRemove"
  | "PreCompact"
  | "PostCompact"
  | "Elicitation"
  | "ElicitationResult"
  | "BeforeToolSelection"
  | "LspDiagnostics"
  | "SessionDiff"
  | "SessionStatus"
  | "MemoryRead"
  | "MemoryWrite"
  ;

/** Every canonical event name, in catalog order. */
export const allCanonicalEvents: readonly CanonicalEvent[] = [
  "SessionStart",
  "SessionEnd",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "PostToolUseFailure",
  "PermissionRequest",
  "PermissionDenied",
  "Notification",
  "SubagentStart",
  "SubagentStop",
  "TaskCreated",
  "TaskCompleted",
  "Stop",
  "StopFailure",
  "TeammateIdle",
  "InstructionsLoaded",
  "ConfigChange",
  "CwdChanged",
  "FileChanged",
  "WorktreeCreate",
  "WorktreeRemove",
  "PreCompact",
  "PostCompact",
  "Elicitation",
  "ElicitationResult",
  "BeforeToolSelection",
  "LspDiagnostics",
  "SessionDiff",
  "SessionStatus",
  "MemoryRead",
  "MemoryWrite",
];

// Named constants, one per event, mirroring axon.Event<Name> in events_gen.go.
/** Session begins or resumes. */
export const EventSessionStart: CanonicalEvent = "SessionStart";
/** Session terminates (graceful or forced). */
export const EventSessionEnd: CanonicalEvent = "SessionEnd";
/** User submits a prompt before the model processes it. */
export const EventUserPromptSubmit: CanonicalEvent = "UserPromptSubmit";
/** Before a tool call executes; handler can block. */
export const EventPreToolUse: CanonicalEvent = "PreToolUse";
/** After a tool call succeeds. */
export const EventPostToolUse: CanonicalEvent = "PostToolUse";
/** After a tool call fails. */
export const EventPostToolUseFailure: CanonicalEvent = "PostToolUseFailure";
/** Permission dialog appears for a tool call. */
export const EventPermissionRequest: CanonicalEvent = "PermissionRequest";
/** Tool call denied by auto-mode classifier or user. */
export const EventPermissionDenied: CanonicalEvent = "PermissionDenied";
/** CLI sends a user-facing notification. */
export const EventNotification: CanonicalEvent = "Notification";
/** Subagent spawned by the main agent. */
export const EventSubagentStart: CanonicalEvent = "SubagentStart";
/** Subagent finishes execution. */
export const EventSubagentStop: CanonicalEvent = "SubagentStop";
/** Task created via TaskCreate tool or equivalent. */
export const EventTaskCreated: CanonicalEvent = "TaskCreated";
/** Task marked completed. */
export const EventTaskCompleted: CanonicalEvent = "TaskCompleted";
/** Model finishes responding for this turn. */
export const EventStop: CanonicalEvent = "Stop";
/** Turn ends due to API error or internal failure. */
export const EventStopFailure: CanonicalEvent = "StopFailure";
/** Agent-team teammate going idle (multi-agent only). */
export const EventTeammateIdle: CanonicalEvent = "TeammateIdle";
/** CLAUDE.md or equivalent rules file loaded/reloaded. */
export const EventInstructionsLoaded: CanonicalEvent = "InstructionsLoaded";
/** Config file changes during a session. */
export const EventConfigChange: CanonicalEvent = "ConfigChange";
/** Working directory changes (e.g. via cd). */
export const EventCwdChanged: CanonicalEvent = "CwdChanged";
/** Watched file changes on disk. */
export const EventFileChanged: CanonicalEvent = "FileChanged";
/** Git worktree created. */
export const EventWorktreeCreate: CanonicalEvent = "WorktreeCreate";
/** Git worktree removed. */
export const EventWorktreeRemove: CanonicalEvent = "WorktreeRemove";
/** Before context compaction begins. */
export const EventPreCompact: CanonicalEvent = "PreCompact";
/** After context compaction completes. */
export const EventPostCompact: CanonicalEvent = "PostCompact";
/** MCP server requests user input. */
export const EventElicitation: CanonicalEvent = "Elicitation";
/** User responds to MCP elicitation request. */
export const EventElicitationResult: CanonicalEvent = "ElicitationResult";
/** Before model picks which tool to call (Gemini-only). */
export const EventBeforeToolSelection: CanonicalEvent = "BeforeToolSelection";
/** LSP diagnostics arrived (OpenCode-only). */
export const EventLspDiagnostics: CanonicalEvent = "LspDiagnostics";
/** Session code diff computed (OpenCode-only). */
export const EventSessionDiff: CanonicalEvent = "SessionDiff";
/** Session status transition (OpenCode-only). */
export const EventSessionStatus: CanonicalEvent = "SessionStatus";
/** Derived event — Read tool call targeting a canonical memory path (CLAUDE.md, MEMORY.md, .claude/memory/**, agent memory). */
export const EventMemoryRead: CanonicalEvent = "MemoryRead";
/** Derived event — Write/Edit/NotebookEdit tool call targeting a canonical memory path. Same path regex as MemoryRead. */
export const EventMemoryWrite: CanonicalEvent = "MemoryWrite";
